## CS559: Homework #1

Assignment #1: due on **2/23/2021 by 11:59 PM**. 
- Change the file name as *YourName*_S21_CS559_HW1
- Submit the assignment both in format of *ipynb* and *html*. 
    - You can export the file as *html* as `File`>`Download as`>`HTML`. The assignment should be own work and must not be shared between classmates. 
- You **do not need to compress** the files. You can submit individual files.
- This assignment focuses on two topics - linear algebra and data pre-processing. 
    - For linear algebra questions, when the question says "implement", you cannot use any built-in functions.
- This assignment should an individual work. Do not collaborate with classmates or get help from 3rd person. You may surf internet if you need to. Then site the reference. 

### Problem 1 [10 pts]
- Implement a function `dot_product` to calculate the dot product of two 1 by n arrays. [6 pts] 
```
a = array([1, 2, 3, 4])
b = array([2, 3, 4, 5])
dot_product(a,b) = 40
```

In [12]:
### Code Starts Here
import numpy as np
def dot_product(a, b):
    assert a.shape==b.shape
    res = 0
    for i in range(a.shape[0]):
            res = res + a[i]*b[i]
    return res

c = np.array([1, 2, 3, 4])
d = np.array([2, 3, 4, 5])
res1=dot_product(c,d)
print(res1)

40


- Test your code after generating two random 1 by 10 arrays. [4 pts]

In [13]:
### Code Starts Here
x=np.random.randn(10)
y=np.random.randn(10)
res2=dot_product(x,y)
print(res2)



-5.684838654140022


### Problem 2 [10 pts]
- Consider three vectors ${\bf x}_1=(1,3), {\bf x}_2=(-1,5)$, and ${\bf x}_3=(0,7)$. Find the distance of each point from the **origin**. [4 pts]

In [14]:
### Code Starts Here
import numpy as np

def distance(x):
    res1 = np.sqrt((x[0]-0)*(x[0]-0)+(x[1]-0)*(x[1]-0))
    return res1

x1=np.array([1,3])
x2=np.array([-1,5])
x3=np.array([0,7])

print(distance(x1))
print(distance(x2))
print(distance(x3))

3.1622776601683795
5.0990195135927845
7.0


- Rotate the coordinates by 35 degress in counter clockwise. [4 pts]

In [15]:
### Code Starts Here
import numpy as np
def rotate(x,de):
    degree=np.array([[np.cos(de),-np.sin(de)], [np.sin(de),np.cos(de)]])
    res2=np.zeros(2)
    res2[0]=x[0]*degree[0,0]+x[1]*degree[0,1]
    res2[1]=x[0]*degree[1,0]+x[1]*degree[1,1]
    return res2

x1=np.array([1,3])
x2=np.array([-1,5])
x3=np.array([0,7])

print(rotate(x1,np.pi*35/180))
print(rotate(x2,np.pi*35/180))
print(rotate(x3,np.pi*35/180))

[-0.90157726  3.03103257]
[-3.68703423  3.52218379]
[-4.01503505  5.73406431]


- Magnify the area by 4 times. [2 pts]

In [10]:
### Code Starts Here
import numpy as np
def magnify(x):
    res3=x*2
    return res3

x1=np.array([1,3])
x2=np.array([-1,5])
x3=np.array([0,7])

print(magnify(x1))
print(magnify(x2))
print(magnify(x3))


[2 6]
[-2 10]
[ 0 14]


### Problem 3 [20 pts]
- Implement a function `mat_product` to calculate the matrix product of two n by n arrays. [8 pts] For example:


$A = \begin{bmatrix} 1 & 3 & 0 \\ 2 & 0 & 2 \\ 1 & 1 & 4 \end{bmatrix}$ and $A\cdot A=\begin{bmatrix} 7 & 3 & 6 \\ 4 & 8 & 8 \\ 7 & 8 & 18 \end{bmatrix}$

    mat_product(A,A)=?

In [17]:
### Code Starts Here
import numpy as np
def mat_product(x,y):
    assert x.shape[1]==y.shape[0]
    res=np.zeros((x.shape[0],y.shape[1]))
    for i in range(x.shape[0]):
        for j in range(y.shape[1]):
            for k in range(x.shape[1]):
                res[i,j]+= x[i,k] * y[k,j]
    return res

a = np.array([[1, 3, 0], [2, 0, 2], [1, 1, 4]])
a1 = np.array([[7, 3, 6], [4, 8, 8], [7, 8, 18]])
print(mat_product(a, a))
print(mat_product(a, a1))

[[ 7.  3.  6.]
 [ 4.  8.  8.]
 [ 7.  7. 18.]]
[[19. 27. 30.]
 [28. 22. 48.]
 [39. 43. 86.]]


- Test your code after generating two random 4 by 4 matrices, ${\bf X}$ and ${\bf Y}$. [4 pts]

In [18]:
### Test Starts Here
x=np.random.randn(4,4)
y=np.random.randn(4,4)
print(mat_product(x,y))

[[-0.4062008   3.63068668 -0.07651341  2.97718566]
 [ 1.10975965  1.67190977 -0.48671398  0.60178037]
 [-1.82383197 -3.52304997  0.74926507 -1.93905732]
 [-1.85125246 -1.17017018  0.64598612  0.2543719 ]]


- Inplement a function `mat_transpose` that transposes ${\bf X}$ and use the `mat_product` function to find the matrice of product: $Z={\bf X}^T\cdot{\bf Y}$ [8 pts]

        Z=mat_product(mat_transpose(X),Y)

In [19]:
### Code Starts Here
def mat_transpose(x):
    res1=np.zeros((x.shape[1],x.shape[0]))
    for i in range(x.shape[1]):
        for j in range(x.shape[0]):
            res1[i,j]=x[j,i]
    return res1

z=mat_product(mat_transpose(x),y)
print(z)

[[-1.25637575 -0.07789556  0.14133668  0.206394  ]
 [ 0.14924853  0.14543763 -0.22921208 -0.19822382]
 [-2.38078418  0.75311662  0.92139572  2.11712967]
 [ 3.74160196  0.44042543 -0.88740769 -1.46373562]]


### Problem 4 [30 pts]
- In this question, we will use the csv file **Temp.csv**. This question task is a process of exploratory data ansysis (EDA) to learn about data itself. Read it into a data frame, call it `Temp`. (Import the packages you think you need). [4 pts]

In [38]:
### Code Starts Here
import pandas as pd
Temp=pd.read_csv('Temp.csv')
Temp.head(11)

City        State  Temperature
0         NYC     New York           67
1      Albany     New York           49
2     Buffalo     New York           38
3    Hartford  Connecticut           63
4  Bridgeport  Connecticut           58
5      Treton   New Jersey           72
6      Newark   New Jersey           68

- We learned that the temperature at New Haven, Connecticut is currently 58 degree fahrenheit. Add this information into the DataFrame.[4 pts]

In [39]:
### Code Starts Here
data=pd.DataFrame({'City':['New Haven'],'State':['Connecticut'],'Temperature':[58]})
Temp = pd.concat([Temp,data],ignore_index=True)
Temp.head(9)

City        State  Temperature
0         NYC     New York           67
1      Albany     New York           49
2     Buffalo     New York           38
3    Hartford  Connecticut           63
4  Bridgeport  Connecticut           58
5      Treton   New Jersey           72
6      Newark   New Jersey           68
7   New Haven  Connecticut           58

- Replace the names of the states by their abbreviations. [4 pts] That is 
    - Connecticut --> CT
    - New Jersey  --> NJ
    - New York    --> NY

In [40]:
### Code Starts Here

Temp.replace('Connecticut', 'CT', inplace=True)
Temp.replace('New Jersey', 'NJ', inplace=True)
Temp.replace('New York', 'NY', inplace=True)
Temp.head(9)

City State  Temperature
0         NYC    NY           67
1      Albany    NY           49
2     Buffalo    NY           38
3    Hartford    CT           63
4  Bridgeport    CT           58
5      Treton    NJ           72
6      Newark    NJ           68
7   New Haven    CT           58

- Select the rows in New York. [2 pts]

In [41]:
### Code Starts Here
ny=Temp.loc[Temp['State']=='NY',:]
ny.head()

City State  Temperature
0      NYC    NY           67
1   Albany    NY           49
2  Buffalo    NY           38

- What is the average of the temperature of cities in NY? [4 pts]

In [42]:
### Code Starts Here
nymean=ny['Temperature'].mean(axis=0)
print('The average temperature in NY is ' ,str(nymean))

The average temperature in NY is  51.333333333333336


- Find the mean and the standard deviation of the temperature of each state. [4 pts]

In [43]:
### Code Starts Here
nymean=ny['Temperature'].mean(axis=0)
print('The average temperature in NY is ' ,str(nymean))
nystd=ny['Temperature'].std(axis=0)
print('The deviation of the temperature in NY is ' ,str(nystd))


ct=Temp.loc[Temp['State']=='CT',:]
ctmean = ct['Temperature'].mean(axis=0)
print('The average temperature in CT is ',str(ctmean))
ctstd=ct['Temperature'].std(axis=0)
print('The deviation of the temperature in CT is ' ,str(ctstd))

nj=Temp.loc[Temp['State']=='NJ',:]
njmean = nj['Temperature'].mean(axis=0)
print('The average temperature in NJ is ' ,str(njmean))
njstd=nj['Temperature'].std(axis=0)
print('The deviation of the temperature in NJ is ' ,str(njstd))


The average temperature in NY is  51.333333333333336
The deviation of the temperature in NY is  14.6401275039985
The average temperature in CT is  59.666666666666664
The deviation of the temperature in CT is  2.8867513459481287
The average temperature in NJ is  70.0
The deviation of the temperature in NJ is  2.8284271247461903


- Create a data frame `Capital`, with two columns: State and Capital. [4 pts] 

    We know the capital of each state: 
    - Connecticut --> Hartford
    - New Jersey  --> Treton
    - New York    --> Albany
    
|| State| Capital|
| :-: |:---: | :---:|
| 0| CT  | Hartford|
| 1| NJ | Treton|
| 2| NY| Albany|

In [44]:
### Code Starts Here
Capital=pd.DataFrame({'State':['CT','NJ','NY'],'Capital':['Hartford','Treton','Albany']})
cp = ['State', 'Capital']
Capital = Capital[cp]
Capital.head()

State   Capital
0    CT  Hartford
1    NJ    Treton
2    NY    Albany

- Mutate a new boolean column, `Capital`, to `Temp`, which is `True` if the city in the row is the capital of the state, else `False`. [4 pts]

In [45]:
### Code Starts Here
Temp['Captical']=Temp['City'].isin(Capital['Capital'])
Temp.head(9)

City State  Temperature  Captical
0         NYC    NY           67     False
1      Albany    NY           49      True
2     Buffalo    NY           38     False
3    Hartford    CT           63      True
4  Bridgeport    CT           58     False
5      Treton    NJ           72      True
6      Newark    NJ           68     False
7   New Haven    CT           58     False

### Problem 5 [30 pts]

- a. Load the Gross Domestic Product data for the 190 ranked countries in the file **GDP.csv**. Load **Country.csv** into a DataFrame. [6 pts]

In [46]:
### Code Starts Here
import pandas as pd
gdp=pd.read_csv('GDP.csv',encoding='ISO-8859-1',skiprows=5,nrows=190,usecols=[0,1,3,4],header=None)
city=pd.read_csv('Country.csv',encoding='ISO-8859-1')
gdp.columns=['CountryCode','Ranking','County','GDP']
gdp.head(11)

CountryCode  Ranking              County           GDP
0          USA        1       United States   16,244,600 
1          CHN        2               China    8,227,103 
2          JPN        3               Japan    5,959,718 
3          DEU        4             Germany    3,428,131 
4          FRA        5              France    2,612,878 
5          GBR        6      United Kingdom    2,471,784 
6          BRA        7              Brazil    2,252,664 
7          RUS        8  Russian Federation    2,014,775 
8          ITA        9               Italy    2,014,670 
9          IND       10               India    1,841,710 
10         CAN       11              Canada    1,821,424

- b. Match the data based on the country shortcode. How many of the IDs match? [6 pts]

In [47]:
### Code Starts Here
mer = pd.merge(gdp,city)
print(len(match))

189


- c. Sort the data frame in descending order by GDP rank. What is the 13th country in the resulting data frame? (Note: GDP formats as 123,456,789.) [6 pts]

In [48]:
### Code Starts Here
mer['GDP'] = mer['GDP'].apply(lambda x: x.replace(",", "")).astype("float64")
mer.sort_values(by='GDP',ascending=False)
mer.reset_index()
print(match.loc[12,'County'])


Spain


- d. What is the average GDP for the "High income: OECD" and "High income: nonOECD" group? [6 pts]

In [49]:
### Code Starts Here
oecd = mer['GDP'].groupby(mer['Income Group']).mean()
print('High income: OECD ',oecd['High income: OECD'])
print('High income: nonOECD ',oecd['High income: nonOECD'])

High income: OECD  1483917.1333333333
High income: nonOECD  104349.82608695653


- e. What is the average GDP for different income groups and regions? [6 pts]

In [50]:
### Code Starts Here
region= mer.groupby(['Income Group','Region'])['GDP']
print(region.mean())

Income Group          Region                    
High income: OECD     East Asia & Pacific           2.197268e+06
                      Europe & Central Asia         7.567044e+05
                      Middle East & North Africa    2.582170e+05
                      North America                 9.033012e+06
High income: nonOECD  East Asia & Pacific           1.496240e+05
                      Europe & Central Asia         2.776660e+04
                      Latin America & Caribbean     2.795480e+04
                      Middle East & North Africa    2.142531e+05
                      North America                 5.474000e+03
                      Sub-Saharan Africa            1.769700e+04
Low income            East Asia & Pacific           8.154667e+03
                      Europe & Central Asia         6.723500e+03
                      Latin America & Caribbean     7.843000e+03
                      South Asia                    5.193833e+04
                      Sub-Saharan Africa 